### ISSUE TITLE
model weight doesn't match 

### ISSUE THREAD

**Issue by cook-kuk** [PaccMann/paccmann_rl#1]
I follow the tutorial in your repo.  but it doesn't work. I got error message like this. 

command : python code\paccmann_generator\examples\IC50\train_paccmann_rl.py models\svae models\pvae models\paccmann data\gdsc_transcriptomics_for_conditional_generation.pkl code\paccmann_generator\examples\IC50\example_params.json paccmann_rl breast

RuntimeError: Error(s) in loading state_dict for TeacherVAE:
        Missing key(s) in state_dict: "encoder.embedding.weight", "encoder.backward_stackgru.stack_controls_layer.weight", "encoder.backward_stackgru.stack_controls_layer.bias", "encoder.backward_stackgru.stack_input_layer.weight", "encoder.backward_stackgru.stack_input_layer.bias", "encoder.backward_stackgru.e
mbedding.weight", "encoder.backward_stackgru.gru.weight_ih_l0", "encoder.backward_stackgru.gru.weight_hh_l0", "encoder.backward_stackgru.gru.bias_ih_l0", "encoder.backward_stackgru.gru.bias_hh_l0", "encoder.backward_stackgru.gru.weight_ih_l1", "encoder.backward_stackgru.gru.weight_hh_l1", "encoder.backward_stac
kgru.gru.bias_ih_l1", "encoder.backward_stackgru.gru.bias_hh_l1", "decoder.embedding.weight", "decoder.output_layer.weight", "decoder.output_layer.bias".
        Unexpected key(s) in state_dict: "encoder.encoder.weight", "encoder.decoder.weight", "encoder.decoder.bias", "encoder.gru.weight_ih_l0_reverse", "encoder.gru.weight_hh_l0_reverse", "encoder.gru.bias_ih_l0_reverse", "encoder.gru.bias_hh_l0_reverse", "encoder.gru.weight_ih_l1_reverse", "encoder.gru.weight
_hh_l1_reverse", "encoder.gru.bias_ih_l1_reverse", "encoder.gru.bias_hh_l1_reverse", "decoder.encoder.weight", "decoder.decoder.weight", "decoder.decoder.bias", "decoder.gru.weight_ih_l0_reverse", "decoder.gru.weight_hh_l0_reverse", "decoder.gru.bias_ih_l0_reverse", "decoder.gru.bias_hh_l0_reverse", "decoder.gr
u.weight_ih_l1_reverse", "decoder.gru.weight_hh_l1_reverse", "decoder.gru.bias_ih_l1_reverse", "decoder.gru.bias_hh_l1_reverse".
        size mismatch for encoder.gru.weight_ih_l1: copying a param with shape torch.Size([768, 512]) from checkpoint, the shape in current model is torch.Size([768, 256]).
        size mismatch for decoder.gru.weight_ih_l1: copying a param with shape torch.Size([768, 512]) from checkpoint, the shape in current model is torch.Size([768, 256]).

I presume that there is a problem with the model or model information you provided.

**Comment by drugilsberg** [comment]
Thanks a lot for opening the issue, we will look into this and get back to you.

**Comment by jannisborn** [comment]
@SeunghoKuk-dev Thanks for your interest!

This bug probably arises because the `README.md` is out of date since the dependencies like `paccmann_chemistry` have advanced since the release. Please `cd` into each individual repo listed [here](https://github.com/PaccMann/paccmann_rl#clone-the-repos) (paccmann_predictor, paccmann_chemistry, paccmann_generator and paccmann_omics) and do:
`git checkout 0.0.1`.

Then try to re-run the code and let us know whether it fixed the issue.

**Comment by drugilsberg** [comment]
In case this fix works I opened a PR implementing the change in the tutorial: https://github.com/PaccMann/paccmann_rl/pull/2.
Let us know @SeunghoKuk-dev .

**Comment by jannisborn** [comment]
This change of repo version may also help resolving the issue in `paccmann_chemistry`: https://github.com/PaccMann/paccmann_chemistry/issues/15

**Comment by jannisborn** [comment]
I consider this solved given your comment in #3, please reopen if applicable @SeunghoKuk-dev
